dz-1
Papai145/dz-HTML-CSS pull request #1
Opened 2024-05-13 17:33 UTC by Papai145

2024-05-15 07:35 UTC, GitEsense requested changes
Необходимо внести правки. Посмотрите комментарии

2024-05-15 07:35 UTC, GitEsense commented on 1-Blog/1-html-blog/index.html
> +    </footer>
Вот тут что-то явно не то...
по иерархии у нас как правило идёт "header" - "main" - "footer"
следовательно тут у нас должно иметь вид что-то вроде
header
   nav
       ul
           li
           li
           li

Так же каждый элемент списка - это ссылка, а "В мой блог" - это ссылка с иконкой логотипом и её хорошо бы вынести за nav меню

2024-05-15 07:35 UTC, GitEsense commented on 1-Blog/1-html-blog/index.html
> +      </article>
Вот тут уже можно было бы взять section вместо article, а вместо заголовка 2-го уровня воспользоваться так же параграфом

2024-05-15 07:35 UTC, GitEsense commented on 1-Blog/1-html-blog/index.html
> +      </article>
Достаточно было бы сделать единый артикл и выделить 2 section, первая на картинку (исключительно обёртка, но может существовать отдельно), второй для текстовой части
```html
<article>
   <img>
   <section>
      <p>Текст...</p>
      <p>Текст...</p>
      <p>Текст...</p>
   </section>
</article>
```

2024-05-16 06:50 UTC, GitEsense commented on 1-Blog/1-html-blog/index.html
> +    </footer>
> вопрос только в иконке.как сделать

Иконку можно выгрузить с фигмы и сделать как картинку, можно стилизовать span (дать padding и background), можно как блок с шириной и высотой и так же фоном

2024-05-18 07:19 UTC, Papai145 commented on 1-Blog/1-html-blog/index.html
> +    </footer>
> > вопрос только в иконке.как сделать
> 
> Иконку можно выгрузить с фигмы и сделать как картинку, можно стилизовать span (дать padding и background), можно как блок с шириной и высотой и так же фоном

Сделал ссылку с иконкой

2024-05-20 08:40 UTC, GitEsense approved these changes
Вот теперь всё супер!

2024-05-20 16:41 UTC, merged